[[projects]]
id = 1
title = "coffeebean"
description = "Writing a compiler in Rust."
date = "January 2024"
url = "https://github.com/dasShounak/coffeebean"
tools = ["rust"]

[[projects]]
id = 2
title = "Cloud-based SOC lab"
description = "A SOC lab built on Microsoft Azure with Sentinel to simulate a real-world environment to monitor brute-force attacks in real time."
date = "April 2025"
url = "https://shounakdas.netlify.app/blog/2025-04-30-building-a-cloud-based-home-soc-lab-with-microsoft-sentinel/"
tools = ["azure","KQL"]


[[projects]]
id = 3
title = "bettercp"
description = "A command line tool written in Rust as an alternative for `cp` command"
date = "March 2023"
url = "https://github.com/dasShounak/bettercp"
tools = ["rust"]


